### ISSUE TITLE
How to recognize properties and methods are public or private on ES6 classes

### ISSUE THREAD

**Issue by chentsulin** [4Catalyzer/farce#30]
Use `StateStorage` as example:

```js
export default class StateStorage {
  constructor(farce, namespace) {
    this.getFallbackLocationKey = farce.createHref;
    this.stateKeyPrefix = `${namespace}|`;
  }

  read(location, key) {
   
  }

  save(location, key, value) {
   
  }

  getStateKey(location, key) {
   
  }
}
```

In my view, `this.getFallbackLocationKey`, `this.stateKeyPrefix` and `this.getStateKey` never intentionally be public apis (they are missing in the docs), but it can be easily accessed by user.

Maybe we can improve this by adding some underscore prefixes:

```js
_getStateKey(location, key)
```

or adding some comment notations:

```js
// @private
getStateKey(location, key)
```

Any ideas?

**Comment by taion** [comment]
The underscores sound like a good idea. I think I avoided doing so out of slavish adherence to Airbnb linting rules, but they really do make sense here.
