### ISSUE TITLE
Transition Hooks shouldn't be able to fail and break transitions

### ISSUE THREAD

**Issue by tberman** [4Catalyzer/farce#39]
RIght now, if a transition hook throws an error, the transition fails. This seems bad to me, but open to other thoughts!

**Comment by taion** [comment]
It breaks navigation forever or something? That's probably not ideal. What do you think should happen?

**Comment by tberman** [comment]
It seems to break the current transition, and if the condition repeats forever, then navigation is broken forever. We encountered it via someone doing some stuff w/ ghostery.

I am not sure what I would expect? Page to transition and error to be logged maybe?

**Comment by taion** [comment]
Does the error get swallowed? It's not obviously wrong for transitions with hooks that throw errors to block the transition.

**Comment by tberman** [comment]
As far as I can tell the error never pops out anywhere that you can catch it, so you have to try/catch in your code in case you are doing something that may fail.

It feels weird that if I am asking for an informative transition hook that it can block it.

**Comment by taion** [comment]
Let me try to reproduce this locally. We definitely shouldn't swallow the error.

**Comment by taion** [comment]
Sorry for the delay here. I'm working on this now in #52. The PR does exactly what is proposed here – on an exception in a transition hook, emit a warning, then allow the transition to proceed.
