### ISSUE TITLE
[question] why not encapsulate the locationReducer inside the instrument.js

### ISSUE THREAD

**Issue by haohcraft** [4Catalyzer/farce#8]
According to how Redux Dev Tool's instrument.js and found [this](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L598), Just curious why you guys not try to liftreducer in the instrument.js instead of wire it up in the app.js level.

is there any concern/issue you ran into?

**Comment by taion** [comment]
I'm not sure what you mean. `locationReducer` is just a normal reducer that users can combine into their existing reducers if they want to listen to the current location. I don't even directly use it.
